name: Check Dependencies b/w jobs
on:
  workflow_dispatch:
  push:
    branches: master
jobs:
  first_job:
    name: first_job
    runs-on: ubuntu-latest
    steps:
      - run: echo "first job completed."
      - id: set_outputs
        # run: echo "::set-output name=first_job_completed::yes"
        run: |
          echo "first_job_completed=yes" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.set_outputs.outputs.first_job_completed }}"
    outputs:
      first_job_output: ${{ steps.set_outputs.outputs.first_job_completed }}

  second_job:
    name: second_job
    runs-on: ubuntu-latest
    needs: [ first_job ]
    if: ${{ success() }} 
    # if: ${{ needs.first_job.outputs.first_job_output == 'yes' && github.event_name == 'workflow_dispatch'}} 
    steps:
      - env:
          first_job_status : ${{ needs.first_job.outputs.first_job_output }}
        run: |
          echo "$first_job_status"
      - run: |
          echo "second job completed"

  third_job:
    name: third_job
    runs-on: ubuntu-latest
    needs: [ first_job, second_job ]
    if: ${{ success() }}
    # if: needs.second_job.result == 'success' || needs.second_job.result == 'skipped'
    steps: 
      - run: echo "third job completed"
