name: Environment Read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Deploy'
        type: choice
        options:
          - scratch-alpha
          - production
env:
  ENVIRONMENT: ${{ github.event.inputs.environment }}
jobs:
  configuration:
    name: Configure Environment
    runs-on: ubuntu-latest

    steps:
      - name: Environment
        run: |
          if [[ "${{env.ENVIRONMENT}}" == "production" ]]; then
            echo "Using Production"
          else
            echo "Using Non Production"
          fi
