name: Environment Read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Deploy'
        type: choice
        options:
          - scratch-alpha
          - production
env:
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  ACCOUNT: non-production
jobs:
  configuration:
    name: Configure Environment
    runs-on: ubuntu-latest

    steps:
      - name: Environment
        run: |
          if [[ "${{env.ENVIRONMENT}}" == "production" ]]; then
            echo "ACCOUNT=production" >> $GITHUB_ENV
            echo "Using Production"
          else
            echo "Using Non Production"
          fi

      - name: Use Account
        run: |
          echo "The account type is $ACCOUNT from GHE"
          echo "The account type is ${{ env.ACCOUNT }} from local environment"
  print-environment:
    needs: [configuration] 
    name: Print Environment
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: |
          echo "The account type is $ACCOUNT from GHE"
          echo "The account type is ${{ env.ACCOUNT }} from local environment"
