name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      region:
        required: false
        default: us-east-1
        type: choice
        options:
          - us-east-1
          - us-east-2
        
env:
  REGION: ${{ inputs.region }}
  REPOSITORY_URL: ''

jobs:
  setting_variables:
    runs-on: ubuntu-latest    
    steps:
      - id: set-region
        if: ${{ env.REGION == ''}}
        run: |
          echo "REGION=us-east-1" >> $GITHUB_OUTPUT
          echo "REPOSITORY_URL=dkr.ecr.$REGION.amazonaws.com/descriptionchangeprocessor"  >> $GITHUB_OUTPUT
          
      - if: ${{ env.REGION != ''}}
        run: |
          echo "REPOSITORY_URL=dkr.ecr.$REGION.amazonaws.com/descriptionchangeprocessor"  >> $GITHUB_OUTPUT
    
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
          echo "Region=$REGION"
          echo "Repository Url=$REPOSITORY_URL"
        env:
          First_Name: ${{ inputs.region }}
