name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: branch to deploy
        
      region:
        required: false
        default: us-east-1
        type: choice
        options:
          - us-east-1
          - us-east-2
        
env:
  REGION: ${{ inputs.region }}
  BRANCH: ${{ inputs.branch }}

jobs:
  print_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Region Selected
        run: echo $REGION
        
      - name: Branch Selected
        run: echo $BRANCH
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: checking-checkout-feature-gha
      
      - name: Listing files
        shell: bash
        run: ls
