name: Greeting on variable day

on:
  push:
      branches:
        - 'main'
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: 'main'
        description: branch to deploy
        
      region:
        required: false
        default: us-east-1
        type: choice
        options:
          - us-east-1
          - us-east-2
        
env:
  REGION: ${{ inputs.region }}
  BRANCH: ${{ inputs.branch }}
  IMAGE: DesignPatterns

jobs:
  print_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Region Selected
        run: echo $REGION
        
      - name: Branch Selected
        run: echo $BRANCH
      
      - name: Image Namge
        run: echo RepoName $IMAGE
        
      - name: Checkout Branch - ${{ env.BRANCH }}
        uses: actions/checkout@v3
        with: 
          ref: ${{ env.BRANCH }}

      - name: workspace
        run: echo ${{ github.workspace }} - ${{ github.workflow}} - ${{ github.head_ref}}
        
      - name: custom workspace
        working-directory: CreationalPattern
        run: ls

      - name: Listing files
        run: ls
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{env.BRANCH}}
