name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      region:
        required: false
        default: 'us-east-1'
        type: string
        
env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!. Deploying on ${{ env.INPUT_REGION }}"
        env:
          First_Name: Mona
