name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      region:
        required: false
        default: us-east-1
        type: choice
        options:
          - us-east-1
          - us-east-2
        
env:
  REGION: ${{ inputs.region }}

jobs:
  setting_variables:
    runs-on: ubuntu-latest 
      
    steps:
      - id: set-region
        shell: bash
        run: |
          echo "REPOSITORY_URL=dkr.ecr.$REGION.amazonaws.com/descriptionchangeprocessor" >> "$GITHUB_OUTPUT"
    
  greeting_job:
    needs: [setting_variables]
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        shell: bash
        run: |
          RetrievedUrl="${{ needs.setting_variables.outputs.REPOSITORY_URL }}"
          echo "Region=$REGION"
          echo "Repository Url=$RetrievedUrl"
