name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      region:
        required: false
        default: us-east-1
        type: choice
        options:
          - us-east-1
          - us-east-2
        
env:
  REGION: ${{ inputs.region }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.REGION == 'us-east-1'}}
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!."
          echo "region=$REGION"
        env:
          First_Name: ${{ inputs.region }}
